{% set name = "aodhclient" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6ac4547bc7e3a971965cec97da0ba4104b2d22b1cb5d548a3bce1ff5d119519

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - aodh = aodhclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pbr >=1.4
    - cliff >1.16.0
    - osc-lib >=1.0.1
    - oslo.i18n >=1.5.0
    - oslo.serialization >=1.4.0
    - oslo.utils >=2.0.0
    - osprofiler >=1.4.0
    - keystoneauth1 >=1.0.0
    - six
    - pyparsing

test:
  imports:
    - aodhclient
  commands:
    - aodh -h

about:
  home: https://docs.openstack.org/python-aodhclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python client library for Openstack Aodh
  dev_url: https://docs.openstack.org/infra/manual/developers.html

extra:
  recipe-maintainers:
    - tschoonj
